name: Steps Study
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: set-foo
      - name: each step
      - run: echo "foo=bar" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.set-foo.outputs.foo }}
  
